#config/config.yaml
development: &development
  carrier_wave:
    storage: file

production:
  amazon:
    provider: AWS
    bucket: altoros-blog
    aws_access_key_id: ENV['aws_access_key_id']
    aws_secret_access_key: ENV['aws_secret_access_key']
  carrier_wave:
    storage: fog

test:
  <<: *development

